"""Make _password_hash nullable

Revision ID: 911ce1db7910
Revises: 0c724cf6779e
Create Date: 2025-09-27 14:46:07.194810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911ce1db7910'
down_revision = '0c724cf6779e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('instructions',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('instructions',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
